_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 14
    BATCH_SIZE_PER_IMAGE: 128
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 1000
  STEPS: []
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)
DATALOADER:
  NUM_WORKERS: 2
# OUTPUT_DIR: ./logs/test/4/train