_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./weights/model_final_b275ba.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 1000
  STEPS: []
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)
DATALOADER:
  NUM_WORKERS: 2
OUTPUT_DIR: ./logs/cards
